### PR TITLE
Escape title used in an HTML attribute.

### LINKED ISSUE #84: Escape variables used in attributes
If I create a title with a `"` in it, then the generated markup will break in the admin pages.

With:

- Grav v1.7.0-rc.17
- Admin v1.10.0-rc.17

With this markdown file in _/user/pages/test/w3c_:

```md
---
title: '<abbr title="World Wide Web Consortium">W3C</abbr>'
published: true
date: '13-11-2020 16:10'
publish_date: '13-11-2020 16:10'
---

Some content…

```

The generated code becomes:

```html
<b title="<abbr title=" world="" wide="" web="" consortium"="">W3C"&gt;<abbr title="World Wide Web Consortium">W3C</abbr></b>
```

image

In this specific case, I guess removing the HTML tags would make sense.

### PR DESCRIPTION
**Pull request by arkhi**
This closes #84.

(Also use ellipsis instead of `...`)

### CODE REVIEW

**Comment by ricardo118** [comment]
can also be solved using `'title' => htmlspecialchars($child->menu()),` or `'title' => strip_tags($child->menu()),`
on the file
`system\src\Grav\Common\Flex\Types\Pages\PageIndex.php` Line 492

**Comment by arkhi** [comment]
> can also be solved using `'title' => htmlspecialchars($child->menu()),` or `'title' => strip_tags($child->menu()),`
> on the file
> `system\src\Grav\Common\Flex\Types\Pages\PageIndex.php` Line 492

Wouldn’t that would cause the title to be displayed incorrectly or without its semantic?

**Comment by w00fz** [comment]
This is already fixed with https://github.com/getgrav/grav/commit/13965252518bb8a23328a10f47b9b4e49b0d0f1f

**Comment by mahagr** [comment]
Quick comment here, too: title is a text field, it should in no circumstances accept HTML.

**Pull request closed without merging**
